codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "50...100"
  
  status:
    project:
      default:
        target: 30%
        threshold: 5%
        if_ci_failed: error
    
    patch:
      default:
        target: 50%
        threshold: 10%
        if_ci_failed: error

  flags:
    backend:
      paths:
        - backend/src/main/
      carryforward: true
    
    frontend:
      paths:
        - frontend/app/
        - frontend/components/
        - frontend/utils/
      carryforward: true

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  show_carryforward_flags: true

github_checks:
  annotations: true
