GET http://localhost:8080/health

###

GET http://localhost:8080/api/students/allStudents

###

POST http://localhost:8080/api/students/addStudent
Content-Type: application/json

{
  "name": "hahu"
}
###

DELETE http://localhost:8080/api/students/delete/5