CREATE USER scrapper; 
GRANT rds_iam TO scrapper;
GRANT CONNECT ON DATABASE postgres TO scrapper;
GRANT USAGE, CREATE ON SCHEMA public TO scrapper;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO scrapper;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO scrapper;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO scrapper;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO scrapper;
