name: Deploy Frontend

on:
  workflow_call:
    inputs:
      docker_image_tag:
        required: true
        type: string
        description: 'Docker image tag to deploy'
      environment:
        required: false
        type: string
        default: 'production'
        description: 'Deployment environment'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.FRONTEND_EC2_HOST }}
        username: ${{ secrets.FRONTEND_EC2_USER }}
        key: ${{ secrets.FRONTEND_EC2_SSH_KEY }}
        script: |
          docker image prune -a -f
          # Pull the latest image
          # sudo docker pull ${{ secrets.DOCKER_USERNAME }}/tarifffrontend:${{ inputs.docker_image_tag }}
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/tarifffrontend
          sudo echo "Pulled image: ${{ secrets.DOCKER_USERNAME }}/tarifffrontend" >> ~/deploy-frontend.log
          # Stop existing services
          sudo docker compose down || true
          
          # Start services with new image tag
          # sudo IMAGE_TAG=${{ inputs.docker_image_tag }} docker compose up -d
          sudo docker compose up -d