name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  ci:
    uses: ./.github/workflows/cipipeline.yml
    with:
      working-directory: 'frontend'
      node-version: '18'
  
  docker:
    needs: ci
    uses: ./.github/workflows/dockerBuildPush.yml
    with:
      context: './frontend'
      image-name: 'tarifffrontend'
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}